version: "3.2"
services:
  broker:
    image: rabbitmq:management-alpine
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 5672:5672 # port for the daemon API
      - 15672:15672 # port for the RabbitMQ management interface

  pv_sim:
    build: .
    command: ["python3", "./run_pv_sim.py"]
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: reports
        target: /results
    links:
      - broker
    depends_on:
      - broker

  grid:
    build: .
    command: ["python3", "./run_grid.py"]
    stdin_open: true
    tty: true
    links:
      - broker
    depends_on:
      - broker
